export const RUNTIME_MANIFEST = {
  product: "trades-runtime",
  version: "0.3.0",
  author: "Aziel Eliab",
  identity: "Aziel Eliab",
  role: "trades-runtime",
  kind: "shadow-first-operating-intelligence",
  live_backends: false,
  honesty: "Pure/stub TypeScript runtime. BYO local ServiceTitan + ProBooks inbound. Authoring node is not a data custodian. No central dump. No hosted uploader. No phone-home. No ServiceTitan or ProBooks write-back. live_backends false. Pages off. Credentials local only. No production claim.",
  modules: [
    { slug: "ids", path: "src/core/ids.ts", status: "live-pure", summary: "Canonical entity IDs." },
    { slug: "events", path: "src/core/events.ts", status: "live-pure", summary: "Event contracts and idempotency helpers." },
    { slug: "modes", path: "src/core/modes.ts", status: "live-pure", summary: "Per-branch operating modes." },
    { slug: "confidence", path: "src/core/confidence.ts", status: "live-pure", summary: "Confidence ≠ truth." },
    { slug: "chains", path: "src/core/chains.ts", status: "live-pure", summary: "Append-only chains A/B/C/D." },
    { slug: "human-authority", path: "src/core/human-authority.ts", status: "live-pure", summary: "Human overrides win; disagreement preserved." },
    { slug: "actor-registry", path: "src/core/actor-registry.ts", status: "live-pure", summary: "Named roles, branch scope, lock-holder id. Override is not a bare boolean." },
    { slug: "shadow-modes", path: "src/core/shadow-modes.ts", status: "live-pure", summary: "SHADOW-SEALED / SHADOW-VISIBLE / ADVISE-LOCKED." },
    { slug: "trades-coherence", path: "src/inherited/trades-coherence.ts", status: "live-pure", summary: "Primary vs alternate path." },
    { slug: "evidence-packet", path: "src/inherited/evidence-packet.ts", status: "live-pure", summary: "Provenance wrapper; trust ≠ truth." },
    { slug: "decision-gate", path: "src/inherited/decision-gate.ts", status: "live-pure", summary: "High-consequence PASS|REVISE|BLOCK." },
    { slug: "receipt-ledger", path: "src/inherited/receipt-ledger.ts", status: "live-pure", summary: "Hash-chained receipts." },
    { slug: "shadow-engine", path: "src/inherited/shadow-engine.ts", status: "live-pure", summary: "Sealed counterfactual settlement." },
    { slug: "trajectory-engine", path: "src/inherited/trajectory-engine.ts", status: "live-pure", summary: "Morning plan → drift → rebase." },
    { slug: "call-fit", path: "src/domain/call-fit.ts", status: "live-pure", summary: "Dispatch ranking; geography never sole factor." },
    { slug: "job-economics", path: "src/domain/job-economics.ts", status: "live-pure", summary: "Labor × cost × realized contribution." },
    { slug: "cross-trade-matrix", path: "src/domain/cross-trade-matrix.ts", status: "live-pure", summary: "Secondary routing signal only." },
    { slug: "chain-d", path: "src/domain/chain-d.ts", status: "live-pure", summary: "Coordination failure reconstruction." },
    { slug: "workforce-capacity", path: "src/domain/workforce-capacity.ts", status: "live-pure", summary: "Booking blocks and reschedule risk." },
    { slug: "decision-fabric", path: "src/domain/decision-fabric.ts", status: "live-pure", summary: "Multi-pipeline reconcile + Pareto." },
    { slug: "analytics", path: "src/domain/analytics.ts", status: "live-pure", summary: "Mandatory report metadata." },
    { slug: "communications", path: "src/domain/communications.ts", status: "live-pure", summary: "Teams-style channels on the canonical event stream." },
    { slug: "recognition", path: "src/domain/recognition.ts", status: "live-pure", summary: "Quality-gated recognition; never raw revenue alone." },
    { slug: "mission-board", path: "src/domain/mission-board.ts", status: "live-pure", summary: "One branch, one day; KPIs from completions; human can lock a goal." },
    { slug: "fulfillment-machine", path: "src/domain/fulfillment-machine.ts", status: "live-pure", summary: "REQUESTED→RECONCILED on the canonical event stream." },
    { slug: "property-jobs", path: "src/domain/property-jobs.ts", status: "live-pure", summary: "Job attaches to address; completed work appends the improvement ledger." },
    { slug: "pricebook", path: "src/domain/pricebook.ts", status: "live-pure", summary: "ST shadow baseline; ACCEPT/OVERRIDE/LOCK with Chain C receipt." },
    { slug: "truck-stock", path: "src/domain/truck-stock.ts", status: "live-pure", summary: "Location states, van profile, warehouse fulfillment queue." },
    { slug: "weather-demand", path: "src/domain/weather-demand.ts", status: "live-pure", summary: "Three weather windows; lunar weight 0 without lift." },
    { slug: "maintenance-routing", path: "src/domain/maintenance-routing.ts", status: "live-pure", summary: "Demand-first maintenance; tags on Chain C." },
    { slug: "property-record", path: "src/domain/property-record.ts", status: "live-pure", summary: "Living property lifecycle; approved sources only; market data is prior." },
    { slug: "property-improvement-ledger", path: "src/domain/property-improvement-ledger.ts", status: "live-pure", summary: "Improvement ledger; repair cost ≠ resale uplift." },
    { slug: "property-value-engine", path: "src/domain/property-value-engine.ts", status: "live-pure", summary: "Value RANGE + nominal/real; mortgage is demand pressure, not a haircut." },
    { slug: "neighborhood-momentum", path: "src/domain/neighborhood-momentum.ts", status: "live-pure", summary: "Visible-methodology momentum score and condition delta." },
    { slug: "neighborhood-failure-patterns", path: "src/domain/neighborhood-failure-patterns.ts", status: "live-pure", summary: "Pattern is diagnostic prior, not proof of subject defect." },
    { slug: "regional-recalibration", path: "src/domain/regional-recalibration.ts", status: "live-pure", summary: "Geo hierarchy + promotion ladder; weaken thin/stale/conflicted samples." },
    { slug: "property-intelligence-hooks", path: "src/domain/property-intelligence-hooks.ts", status: "live-pure", summary: "Typed integration points; not live backends." },
    { slug: "constitution", path: "src/rules/constitution.ts", status: "live-pure", summary: "Architecture §18 freeze + v0.2 + Property Intelligence v1.0 rules." },
    { slug: "fraggate-inbound", path: "src/spine/fraggate-inbound.ts", status: "live-pure", summary: "FragGate inbound wall. First-class servicetitan / probooks / operator-file / human. Wrapper is not verification. Scrape refused. Silent VERIFIED promotion refused." },
    { slug: "durable-receipts", path: "src/spine/durable-receipts.ts", status: "live-pure", summary: "Append-only JSONL receipts. Process exit does not erase Chain C. Isolate per runtime instance." },
    { slug: "run-action", path: "src/spine/run-action.ts", status: "live-pure", summary: "packet → lock → primary → alternate → coherence → gate → receipt → override → shadow settle." },
    { slug: "servicetitan-shadow", path: "src/spine/servicetitan-shadow.ts", status: "live-pure", summary: "Read-only ST-shaped ingest + hash. Writes refused." },
    { slug: "probooks-shadow", path: "src/spine/probooks-shadow.ts", status: "live-pure", summary: "Read-only ProBooks books/items/costs/vendor ingest + hash. First-class peer inbound. Writes refused." },
    { slug: "inbound-layout", path: "src/spine/inbound-layout.ts", status: "live-pure", summary: "Local BYO paths data/inbound/servicetitan and data/inbound/probooks. Not data/tenants." },
    { slug: "local-inbound-config", path: "src/spine/local-inbound-config.ts", status: "live-pure", summary: "Optional local paths / read endpoints. No cloud account. Credentials stay on the user's machine." },
    { slug: "runtime-isolate", path: "src/spine/runtime-isolate.ts", status: "live-pure", summary: "Separate receipt/ledger files per runtime instance. No shared hosted corpus." },
    { slug: "servicetitan-connector", path: "src/spine/servicetitan-shadow.ts", status: "stub", summary: "Live ServiceTitan writes stay refused." },
    { slug: "probooks-connector", path: "src/spine/probooks-shadow.ts", status: "stub", summary: "Live ProBooks writes stay refused." }
  ]
} as const;
